'use strict';

module.exports = {
    REGISTER_PLURALIZER : 'REGISTER_PLURALIZER',
    REGISTER_TRANSLATION: 'REGISTER_TRANSLATION',
    SET_BASE_LOCALE     : 'SET_BASE_LOCALE',
    SET_LOCALE          : 'SET_LOCALE'
};
